### ISSUE TITLE
Navigation bar not work in responsive mode

### ISSUE THREAD

**Issue by pzmrzy** [dlinsley/jekyll-clarity#1]
## Expected Behavior
When clicks the hamburger icon, a temporary side panel opens with the navigation targets.
## Actual Behavior
The hamburger icon is not clickable
## Steps to Reproduce the Problem
1. Follow the document to serve the website
2. Visit http://localhost:4000 with Safari
3. Click Develop Menu and click enter responsive design mode
4. Click iPhone SE/8/8 Plus
5. Click the hamburger icon in the top left corner

**Comment by dlinsley** [comment]
I don't recall this theme having a hamburger icon currently, did you add one?

**Comment by pzmrzy** [comment]
I go to ask clarity guy, they said it is a clarity UI project, responsive part must work with angular, so I write my own javascript to implement this function.
